package ec.discheca.modelo;
// Generated May 8, 2016 10:10:06 PM by Hibernate Tools 3.6.0



/**
 * AsignacionComprobanteElectronico generated by hbm2java
 */
public class AsignacionComprobanteElectronico  implements java.io.Serializable {


     private Integer idAsignacionComprobanteElectronico;
     private Receptor receptor;
     private ComprobanteElectronico comprobanteElectronico;
     private Boolean vistoReceptorAsignacionComprobanteElectronico;

    public AsignacionComprobanteElectronico() {
    }

	
    public AsignacionComprobanteElectronico(Receptor receptor, ComprobanteElectronico comprobanteElectronico) {
        this.receptor = receptor;
        this.comprobanteElectronico = comprobanteElectronico;
    }
    public AsignacionComprobanteElectronico(Receptor receptor, ComprobanteElectronico comprobanteElectronico, Boolean vistoReceptorAsignacionComprobanteElectronico) {
       this.receptor = receptor;
       this.comprobanteElectronico = comprobanteElectronico;
       this.vistoReceptorAsignacionComprobanteElectronico = vistoReceptorAsignacionComprobanteElectronico;
    }
   
    public Integer getIdAsignacionComprobanteElectronico() {
        return this.idAsignacionComprobanteElectronico;
    }
    
    public void setIdAsignacionComprobanteElectronico(Integer idAsignacionComprobanteElectronico) {
        this.idAsignacionComprobanteElectronico = idAsignacionComprobanteElectronico;
    }
    public Receptor getReceptor() {
        return this.receptor;
    }
    
    public void setReceptor(Receptor receptor) {
        this.receptor = receptor;
    }
    public ComprobanteElectronico getComprobanteElectronico() {
        return this.comprobanteElectronico;
    }
    
    public void setComprobanteElectronico(ComprobanteElectronico comprobanteElectronico) {
        this.comprobanteElectronico = comprobanteElectronico;
    }
    public Boolean getVistoReceptorAsignacionComprobanteElectronico() {
        return this.vistoReceptorAsignacionComprobanteElectronico;
    }
    
    public void setVistoReceptorAsignacionComprobanteElectronico(Boolean vistoReceptorAsignacionComprobanteElectronico) {
        this.vistoReceptorAsignacionComprobanteElectronico = vistoReceptorAsignacionComprobanteElectronico;
    }




}


