package ec.discheca.modelo;
// Generated May 8, 2016 10:10:06 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Certificado generated by hbm2java
 */
public class Certificado  implements java.io.Serializable {


     private Integer idCertificado;
     private Empresa empresa;
     private String rutaCertificado;
     private String tipoCertificado;
     private String estadoCertificado;
     private String claveCertificado;
     private String numeroFirmasCertificado;
     private String ambienteCertificado;
     private Date fechaCreacionCertificado;

    public Certificado() {
    }

	
    public Certificado(Empresa empresa, String rutaCertificado, String tipoCertificado, String estadoCertificado, String claveCertificado, String ambienteCertificado, Date fechaCreacionCertificado) {
        this.empresa = empresa;
        this.rutaCertificado = rutaCertificado;
        this.tipoCertificado = tipoCertificado;
        this.estadoCertificado = estadoCertificado;
        this.claveCertificado = claveCertificado;
        this.ambienteCertificado = ambienteCertificado;
        this.fechaCreacionCertificado = fechaCreacionCertificado;
    }
    public Certificado(Empresa empresa, String rutaCertificado, String tipoCertificado, String estadoCertificado, String claveCertificado, String numeroFirmasCertificado, String ambienteCertificado, Date fechaCreacionCertificado) {
       this.empresa = empresa;
       this.rutaCertificado = rutaCertificado;
       this.tipoCertificado = tipoCertificado;
       this.estadoCertificado = estadoCertificado;
       this.claveCertificado = claveCertificado;
       this.numeroFirmasCertificado = numeroFirmasCertificado;
       this.ambienteCertificado = ambienteCertificado;
       this.fechaCreacionCertificado = fechaCreacionCertificado;
    }
   
    public Integer getIdCertificado() {
        return this.idCertificado;
    }
    
    public void setIdCertificado(Integer idCertificado) {
        this.idCertificado = idCertificado;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getRutaCertificado() {
        return this.rutaCertificado;
    }
    
    public void setRutaCertificado(String rutaCertificado) {
        this.rutaCertificado = rutaCertificado;
    }
    public String getTipoCertificado() {
        return this.tipoCertificado;
    }
    
    public void setTipoCertificado(String tipoCertificado) {
        this.tipoCertificado = tipoCertificado;
    }
    public String getEstadoCertificado() {
        return this.estadoCertificado;
    }
    
    public void setEstadoCertificado(String estadoCertificado) {
        this.estadoCertificado = estadoCertificado;
    }
    public String getClaveCertificado() {
        return this.claveCertificado;
    }
    
    public void setClaveCertificado(String claveCertificado) {
        this.claveCertificado = claveCertificado;
    }
    public String getNumeroFirmasCertificado() {
        return this.numeroFirmasCertificado;
    }
    
    public void setNumeroFirmasCertificado(String numeroFirmasCertificado) {
        this.numeroFirmasCertificado = numeroFirmasCertificado;
    }
    public String getAmbienteCertificado() {
        return this.ambienteCertificado;
    }
    
    public void setAmbienteCertificado(String ambienteCertificado) {
        this.ambienteCertificado = ambienteCertificado;
    }
    public Date getFechaCreacionCertificado() {
        return this.fechaCreacionCertificado;
    }
    
    public void setFechaCreacionCertificado(Date fechaCreacionCertificado) {
        this.fechaCreacionCertificado = fechaCreacionCertificado;
    }




}


