package ec.discheca.modelo;
// Generated May 8, 2016 10:10:06 PM by Hibernate Tools 3.6.0



/**
 * Detalle generated by hbm2java
 */
public class Detalle  implements java.io.Serializable {


     private Integer idDetalle;
     private ComprobanteElectronico comprobanteElectronico;
     private String codigoPrincipalDetalle;
     private String descripcionDetalle;
     private String cantidadDetalle;
     private String precioUnitarioDetalle;

    public Detalle() {
    }

    public Detalle(ComprobanteElectronico comprobanteElectronico, String codigoPrincipalDetalle, String descripcionDetalle, String cantidadDetalle, String precioUnitarioDetalle) {
       this.comprobanteElectronico = comprobanteElectronico;
       this.codigoPrincipalDetalle = codigoPrincipalDetalle;
       this.descripcionDetalle = descripcionDetalle;
       this.cantidadDetalle = cantidadDetalle;
       this.precioUnitarioDetalle = precioUnitarioDetalle;
    }
   
    public Integer getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(Integer idDetalle) {
        this.idDetalle = idDetalle;
    }
    public ComprobanteElectronico getComprobanteElectronico() {
        return this.comprobanteElectronico;
    }
    
    public void setComprobanteElectronico(ComprobanteElectronico comprobanteElectronico) {
        this.comprobanteElectronico = comprobanteElectronico;
    }
    public String getCodigoPrincipalDetalle() {
        return this.codigoPrincipalDetalle;
    }
    
    public void setCodigoPrincipalDetalle(String codigoPrincipalDetalle) {
        this.codigoPrincipalDetalle = codigoPrincipalDetalle;
    }
    public String getDescripcionDetalle() {
        return this.descripcionDetalle;
    }
    
    public void setDescripcionDetalle(String descripcionDetalle) {
        this.descripcionDetalle = descripcionDetalle;
    }
    public String getCantidadDetalle() {
        return this.cantidadDetalle;
    }
    
    public void setCantidadDetalle(String cantidadDetalle) {
        this.cantidadDetalle = cantidadDetalle;
    }
    public String getPrecioUnitarioDetalle() {
        return this.precioUnitarioDetalle;
    }
    
    public void setPrecioUnitarioDetalle(String precioUnitarioDetalle) {
        this.precioUnitarioDetalle = precioUnitarioDetalle;
    }




}


