package ec.discheca.modelo;
// Generated May 8, 2016 10:10:06 PM by Hibernate Tools 3.6.0



/**
 * Detalleadicional generated by hbm2java
 */
public class Detalleadicional  implements java.io.Serializable {


     private int iddetalleAdicional;
     private Producto producto;
     private String nombre;
     private String valor;

    public Detalleadicional() {
    }

	
    public Detalleadicional(int iddetalleAdicional, Producto producto) {
        this.iddetalleAdicional = iddetalleAdicional;
        this.producto = producto;
    }
    public Detalleadicional(int iddetalleAdicional, Producto producto, String nombre, String valor) {
       this.iddetalleAdicional = iddetalleAdicional;
       this.producto = producto;
       this.nombre = nombre;
       this.valor = valor;
    }
   
    public int getIddetalleAdicional() {
        return this.iddetalleAdicional;
    }
    
    public void setIddetalleAdicional(int iddetalleAdicional) {
        this.iddetalleAdicional = iddetalleAdicional;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


