package ec.discheca.modelo;
// Generated May 8, 2016 10:10:06 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private String idEmpresa;
     private String nombreUsuarioClienteEmpresa;
     private String claveUsuarioClienteEmpresa;
     private String nombreComercialClienteEmpresa;
     private String razonSocialClienteEmpresa;
     private String direccionClienteEmpresa;
     private String correoPrincipalClienteEmpresa;
     private String telefonoPrincipalClienteEmpresa;
     private Boolean obligadoContabilidadClienteEmpresa;
     private String numeroResolucionClienteEmpresa;
     private byte[] logoClienteEmpresa;
     private Date fechaRegistroClienteEmpresa;
     private Boolean estadoClienteEmpresa;
     private Set certificados = new HashSet(0);
     private Set secuencials = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String idEmpresa, String nombreUsuarioClienteEmpresa, String claveUsuarioClienteEmpresa) {
        this.idEmpresa = idEmpresa;
        this.nombreUsuarioClienteEmpresa = nombreUsuarioClienteEmpresa;
        this.claveUsuarioClienteEmpresa = claveUsuarioClienteEmpresa;
    }
    public Empresa(String idEmpresa, String nombreUsuarioClienteEmpresa, String claveUsuarioClienteEmpresa, String nombreComercialClienteEmpresa, String razonSocialClienteEmpresa, String direccionClienteEmpresa, String correoPrincipalClienteEmpresa, String telefonoPrincipalClienteEmpresa, Boolean obligadoContabilidadClienteEmpresa, String numeroResolucionClienteEmpresa, byte[] logoClienteEmpresa, Date fechaRegistroClienteEmpresa, Boolean estadoClienteEmpresa, Set certificados, Set secuencials) {
       this.idEmpresa = idEmpresa;
       this.nombreUsuarioClienteEmpresa = nombreUsuarioClienteEmpresa;
       this.claveUsuarioClienteEmpresa = claveUsuarioClienteEmpresa;
       this.nombreComercialClienteEmpresa = nombreComercialClienteEmpresa;
       this.razonSocialClienteEmpresa = razonSocialClienteEmpresa;
       this.direccionClienteEmpresa = direccionClienteEmpresa;
       this.correoPrincipalClienteEmpresa = correoPrincipalClienteEmpresa;
       this.telefonoPrincipalClienteEmpresa = telefonoPrincipalClienteEmpresa;
       this.obligadoContabilidadClienteEmpresa = obligadoContabilidadClienteEmpresa;
       this.numeroResolucionClienteEmpresa = numeroResolucionClienteEmpresa;
       this.logoClienteEmpresa = logoClienteEmpresa;
       this.fechaRegistroClienteEmpresa = fechaRegistroClienteEmpresa;
       this.estadoClienteEmpresa = estadoClienteEmpresa;
       this.certificados = certificados;
       this.secuencials = secuencials;
    }
   
    public String getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(String idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombreUsuarioClienteEmpresa() {
        return this.nombreUsuarioClienteEmpresa;
    }
    
    public void setNombreUsuarioClienteEmpresa(String nombreUsuarioClienteEmpresa) {
        this.nombreUsuarioClienteEmpresa = nombreUsuarioClienteEmpresa;
    }
    public String getClaveUsuarioClienteEmpresa() {
        return this.claveUsuarioClienteEmpresa;
    }
    
    public void setClaveUsuarioClienteEmpresa(String claveUsuarioClienteEmpresa) {
        this.claveUsuarioClienteEmpresa = claveUsuarioClienteEmpresa;
    }
    public String getNombreComercialClienteEmpresa() {
        return this.nombreComercialClienteEmpresa;
    }
    
    public void setNombreComercialClienteEmpresa(String nombreComercialClienteEmpresa) {
        this.nombreComercialClienteEmpresa = nombreComercialClienteEmpresa;
    }
    public String getRazonSocialClienteEmpresa() {
        return this.razonSocialClienteEmpresa;
    }
    
    public void setRazonSocialClienteEmpresa(String razonSocialClienteEmpresa) {
        this.razonSocialClienteEmpresa = razonSocialClienteEmpresa;
    }
    public String getDireccionClienteEmpresa() {
        return this.direccionClienteEmpresa;
    }
    
    public void setDireccionClienteEmpresa(String direccionClienteEmpresa) {
        this.direccionClienteEmpresa = direccionClienteEmpresa;
    }
    public String getCorreoPrincipalClienteEmpresa() {
        return this.correoPrincipalClienteEmpresa;
    }
    
    public void setCorreoPrincipalClienteEmpresa(String correoPrincipalClienteEmpresa) {
        this.correoPrincipalClienteEmpresa = correoPrincipalClienteEmpresa;
    }
    public String getTelefonoPrincipalClienteEmpresa() {
        return this.telefonoPrincipalClienteEmpresa;
    }
    
    public void setTelefonoPrincipalClienteEmpresa(String telefonoPrincipalClienteEmpresa) {
        this.telefonoPrincipalClienteEmpresa = telefonoPrincipalClienteEmpresa;
    }
    public Boolean getObligadoContabilidadClienteEmpresa() {
        return this.obligadoContabilidadClienteEmpresa;
    }
    
    public void setObligadoContabilidadClienteEmpresa(Boolean obligadoContabilidadClienteEmpresa) {
        this.obligadoContabilidadClienteEmpresa = obligadoContabilidadClienteEmpresa;
    }
    public String getNumeroResolucionClienteEmpresa() {
        return this.numeroResolucionClienteEmpresa;
    }
    
    public void setNumeroResolucionClienteEmpresa(String numeroResolucionClienteEmpresa) {
        this.numeroResolucionClienteEmpresa = numeroResolucionClienteEmpresa;
    }
    public byte[] getLogoClienteEmpresa() {
        return this.logoClienteEmpresa;
    }
    
    public void setLogoClienteEmpresa(byte[] logoClienteEmpresa) {
        this.logoClienteEmpresa = logoClienteEmpresa;
    }
    public Date getFechaRegistroClienteEmpresa() {
        return this.fechaRegistroClienteEmpresa;
    }
    
    public void setFechaRegistroClienteEmpresa(Date fechaRegistroClienteEmpresa) {
        this.fechaRegistroClienteEmpresa = fechaRegistroClienteEmpresa;
    }
    public Boolean getEstadoClienteEmpresa() {
        return this.estadoClienteEmpresa;
    }
    
    public void setEstadoClienteEmpresa(Boolean estadoClienteEmpresa) {
        this.estadoClienteEmpresa = estadoClienteEmpresa;
    }
    public Set getCertificados() {
        return this.certificados;
    }
    
    public void setCertificados(Set certificados) {
        this.certificados = certificados;
    }
    public Set getSecuencials() {
        return this.secuencials;
    }
    
    public void setSecuencials(Set secuencials) {
        this.secuencials = secuencials;
    }




}


