package ec.discheca.modelo;
// Generated May 8, 2016 10:10:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idproducto;
     private String codigoProducto;
     private String descripcion;
     private String unidadMedida;
     private String cantidad;
     private String precioCosto;
     private String porcentajeVenta;
     private String precioVenta;
     private String porcentajeVentaDos;
     private String precioVentaDos;
     private String estado;
     private Set detalleadicionals = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String descripcion, String precioVenta, String precioVentaDos) {
        this.descripcion = descripcion;
        this.precioVenta = precioVenta;
        this.precioVentaDos = precioVentaDos;
    }
    public Producto(String codigoProducto, String descripcion, String unidadMedida, String cantidad, String precioCosto, String porcentajeVenta, String precioVenta, String porcentajeVentaDos, String precioVentaDos, String estado, Set detalleadicionals) {
       this.codigoProducto = codigoProducto;
       this.descripcion = descripcion;
       this.unidadMedida = unidadMedida;
       this.cantidad = cantidad;
       this.precioCosto = precioCosto;
       this.porcentajeVenta = porcentajeVenta;
       this.precioVenta = precioVenta;
       this.porcentajeVentaDos = porcentajeVentaDos;
       this.precioVentaDos = precioVentaDos;
       this.estado = estado;
       this.detalleadicionals = detalleadicionals;
    }
   
    public Integer getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUnidadMedida() {
        return this.unidadMedida;
    }
    
    public void setUnidadMedida(String unidadMedida) {
        this.unidadMedida = unidadMedida;
    }
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }
    public String getPrecioCosto() {
        return this.precioCosto;
    }
    
    public void setPrecioCosto(String precioCosto) {
        this.precioCosto = precioCosto;
    }
    public String getPorcentajeVenta() {
        return this.porcentajeVenta;
    }
    
    public void setPorcentajeVenta(String porcentajeVenta) {
        this.porcentajeVenta = porcentajeVenta;
    }
    public String getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(String precioVenta) {
        this.precioVenta = precioVenta;
    }
    public String getPorcentajeVentaDos() {
        return this.porcentajeVentaDos;
    }
    
    public void setPorcentajeVentaDos(String porcentajeVentaDos) {
        this.porcentajeVentaDos = porcentajeVentaDos;
    }
    public String getPrecioVentaDos() {
        return this.precioVentaDos;
    }
    
    public void setPrecioVentaDos(String precioVentaDos) {
        this.precioVentaDos = precioVentaDos;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getDetalleadicionals() {
        return this.detalleadicionals;
    }
    
    public void setDetalleadicionals(Set detalleadicionals) {
        this.detalleadicionals = detalleadicionals;
    }




}


