package com.egastos.modelo.ec;
// Generated 20/06/2017 21:43:07 by Hibernate Tools 4.3.1



/**
 * AsignacionComprobanteElectronico generated by hbm2java
 */
public class AsignacionComprobanteElectronico  implements java.io.Serializable {


     private Integer idAsignacionComprobanteElectronico;
     private ComprobanteElectronico comprobanteElectronico;
     private Receptor receptor;
     private Boolean vistoReceptorAsignacionComprobanteElectronico;

    public AsignacionComprobanteElectronico() {
    }

	
    public AsignacionComprobanteElectronico(ComprobanteElectronico comprobanteElectronico, Receptor receptor) {
        this.comprobanteElectronico = comprobanteElectronico;
        this.receptor = receptor;
    }
      public AsignacionComprobanteElectronico(Receptor receptor,ComprobanteElectronico comprobanteElectronico) {
        this.comprobanteElectronico = comprobanteElectronico;
        this.receptor = receptor;
    }
    public AsignacionComprobanteElectronico(ComprobanteElectronico comprobanteElectronico, Receptor receptor, Boolean vistoReceptorAsignacionComprobanteElectronico) {
       this.comprobanteElectronico = comprobanteElectronico;
       this.receptor = receptor;
       this.vistoReceptorAsignacionComprobanteElectronico = vistoReceptorAsignacionComprobanteElectronico;
    }
   
    public Integer getIdAsignacionComprobanteElectronico() {
        return this.idAsignacionComprobanteElectronico;
    }
    
    public void setIdAsignacionComprobanteElectronico(Integer idAsignacionComprobanteElectronico) {
        this.idAsignacionComprobanteElectronico = idAsignacionComprobanteElectronico;
    }
    public ComprobanteElectronico getComprobanteElectronico() {
        return this.comprobanteElectronico;
    }
    
    public void setComprobanteElectronico(ComprobanteElectronico comprobanteElectronico) {
        this.comprobanteElectronico = comprobanteElectronico;
    }
    public Receptor getReceptor() {
        return this.receptor;
    }
    
    public void setReceptor(Receptor receptor) {
        this.receptor = receptor;
    }
    public Boolean getVistoReceptorAsignacionComprobanteElectronico() {
        return this.vistoReceptorAsignacionComprobanteElectronico;
    }
    
    public void setVistoReceptorAsignacionComprobanteElectronico(Boolean vistoReceptorAsignacionComprobanteElectronico) {
        this.vistoReceptorAsignacionComprobanteElectronico = vistoReceptorAsignacionComprobanteElectronico;
    }




}


