package com.egastos.modelo.ec;
// Generated 20/06/2017 21:43:07 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ComprobanteElectronicoPendiente generated by hbm2java
 */
public class ComprobanteElectronicoPendiente  implements java.io.Serializable {


     private Integer idComprobanteElectronicoPendiente;
     private ComprobanteElectronico comprobanteElectronico;
     private Date fechaEnvioComprobanteElectronicoPendiente;
     private String rutaComprobanteElectronicoPendiente;
     private String mensajeComprobanteElectronicoPendiente;
     private String estadoComprobanteElectronicoPendiente;

    public ComprobanteElectronicoPendiente() {
    }

    public ComprobanteElectronicoPendiente(ComprobanteElectronico comprobanteElectronico, Date fechaEnvioComprobanteElectronicoPendiente, String rutaComprobanteElectronicoPendiente, String mensajeComprobanteElectronicoPendiente, String estadoComprobanteElectronicoPendiente) {
       this.comprobanteElectronico = comprobanteElectronico;
       this.fechaEnvioComprobanteElectronicoPendiente = fechaEnvioComprobanteElectronicoPendiente;
       this.rutaComprobanteElectronicoPendiente = rutaComprobanteElectronicoPendiente;
       this.mensajeComprobanteElectronicoPendiente = mensajeComprobanteElectronicoPendiente;
       this.estadoComprobanteElectronicoPendiente = estadoComprobanteElectronicoPendiente;
    }
   
    public Integer getIdComprobanteElectronicoPendiente() {
        return this.idComprobanteElectronicoPendiente;
    }
    
    public void setIdComprobanteElectronicoPendiente(Integer idComprobanteElectronicoPendiente) {
        this.idComprobanteElectronicoPendiente = idComprobanteElectronicoPendiente;
    }
    public ComprobanteElectronico getComprobanteElectronico() {
        return this.comprobanteElectronico;
    }
    
    public void setComprobanteElectronico(ComprobanteElectronico comprobanteElectronico) {
        this.comprobanteElectronico = comprobanteElectronico;
    }
    public Date getFechaEnvioComprobanteElectronicoPendiente() {
        return this.fechaEnvioComprobanteElectronicoPendiente;
    }
    
    public void setFechaEnvioComprobanteElectronicoPendiente(Date fechaEnvioComprobanteElectronicoPendiente) {
        this.fechaEnvioComprobanteElectronicoPendiente = fechaEnvioComprobanteElectronicoPendiente;
    }
    public String getRutaComprobanteElectronicoPendiente() {
        return this.rutaComprobanteElectronicoPendiente;
    }
    
    public void setRutaComprobanteElectronicoPendiente(String rutaComprobanteElectronicoPendiente) {
        this.rutaComprobanteElectronicoPendiente = rutaComprobanteElectronicoPendiente;
    }
    public String getMensajeComprobanteElectronicoPendiente() {
        return this.mensajeComprobanteElectronicoPendiente;
    }
    
    public void setMensajeComprobanteElectronicoPendiente(String mensajeComprobanteElectronicoPendiente) {
        this.mensajeComprobanteElectronicoPendiente = mensajeComprobanteElectronicoPendiente;
    }
    public String getEstadoComprobanteElectronicoPendiente() {
        return this.estadoComprobanteElectronicoPendiente;
    }
    
    public void setEstadoComprobanteElectronicoPendiente(String estadoComprobanteElectronicoPendiente) {
        this.estadoComprobanteElectronicoPendiente = estadoComprobanteElectronicoPendiente;
    }




}


