package com.egastos.modelo.ec;
// Generated 20/06/2017 21:43:07 by Hibernate Tools 4.3.1



/**
 * Configuracion generated by hbm2java
 */
public class Configuracion  implements java.io.Serializable {


     private Integer idConfiguracion;
     private String nombreConfiguracion;
     private String valorConfiguracion;
     private String ambienteConfiguracion;

    public Configuracion() {
    }

    public Configuracion(String nombreConfiguracion, String valorConfiguracion, String ambienteConfiguracion) {
       this.nombreConfiguracion = nombreConfiguracion;
       this.valorConfiguracion = valorConfiguracion;
       this.ambienteConfiguracion = ambienteConfiguracion;
    }
   
    public Integer getIdConfiguracion() {
        return this.idConfiguracion;
    }
    
    public void setIdConfiguracion(Integer idConfiguracion) {
        this.idConfiguracion = idConfiguracion;
    }
    public String getNombreConfiguracion() {
        return this.nombreConfiguracion;
    }
    
    public void setNombreConfiguracion(String nombreConfiguracion) {
        this.nombreConfiguracion = nombreConfiguracion;
    }
    public String getValorConfiguracion() {
        return this.valorConfiguracion;
    }
    
    public void setValorConfiguracion(String valorConfiguracion) {
        this.valorConfiguracion = valorConfiguracion;
    }
    public String getAmbienteConfiguracion() {
        return this.ambienteConfiguracion;
    }
    
    public void setAmbienteConfiguracion(String ambienteConfiguracion) {
        this.ambienteConfiguracion = ambienteConfiguracion;
    }




}


