package com.egastos.modelo.ec;
// Generated 20/06/2017 21:43:07 by Hibernate Tools 4.3.1



/**
 * Detalleadicional generated by hbm2java
 */
public class Detalleadicional  implements java.io.Serializable {


     private int iddetalleAdicional;
     private String nombre;
     private String valor;
     private int producto;

    public Detalleadicional() {
    }

	
    public Detalleadicional(int iddetalleAdicional, int producto) {
        this.iddetalleAdicional = iddetalleAdicional;
        this.producto = producto;
    }
    public Detalleadicional(int iddetalleAdicional, String nombre, String valor, int producto) {
       this.iddetalleAdicional = iddetalleAdicional;
       this.nombre = nombre;
       this.valor = valor;
       this.producto = producto;
    }
   
    public int getIddetalleAdicional() {
        return this.iddetalleAdicional;
    }
    
    public void setIddetalleAdicional(int iddetalleAdicional) {
        this.iddetalleAdicional = iddetalleAdicional;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public int getProducto() {
        return this.producto;
    }
    
    public void setProducto(int producto) {
        this.producto = producto;
    }




}


