package com.egastos.modelo.ec;
// Generated 20/06/2017 21:43:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Planespago generated by hbm2java
 */
public class Planespago  implements java.io.Serializable {


     private Integer idPlanesPago;
     private Double valor;
     private Integer meses;
     private Set pagoses = new HashSet(0);

    public Planespago() {
    }

    public Planespago(Double valor, Integer meses, Set pagoses) {
       this.valor = valor;
       this.meses = meses;
       this.pagoses = pagoses;
    }
   
    public Integer getIdPlanesPago() {
        return this.idPlanesPago;
    }
    
    public void setIdPlanesPago(Integer idPlanesPago) {
        this.idPlanesPago = idPlanesPago;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public Integer getMeses() {
        return this.meses;
    }
    
    public void setMeses(Integer meses) {
        this.meses = meses;
    }
    public Set getPagoses() {
        return this.pagoses;
    }
    
    public void setPagoses(Set pagoses) {
        this.pagoses = pagoses;
    }




}


